CREATE TABLE IF NOT EXISTS PUBLISHER(
	PUBLISHER_NAME VARCHAR(50) PRIMARY KEY,
	PHONE VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(75) NOT NULL
);



CREATE TABLE IF NOT EXISTS LIBRARY_BRANCH(
	BRANCH_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	BRANCH_NAME VARCHAR(50) UNIQUE,
	BRANCH_ADDRESS VARCHAR(75) NOT NULL
);



CREATE TABLE IF NOT EXISTS BORROWER(
	CARD_NO INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME VARCHAR(50) UNIQUE,
	ADDRESS VARCHAR(75) NOT NULL,
	PHONE VARCHAR(50) NOT NULL
);



CREATE TABLE IF NOT EXISTS BOOK(
	BOOK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	TITLE VARCHAR(50) UNIQUE,
	PUBLISHER_NAME VARCHAR(50),

	FOREIGN KEY(PUBLISHER_NAME) REFERENCES PUBLISHER(PUBLISHER_NAME) ON UPDATE CASCADE
);



CREATE TABLE IF NOT EXISTS BOOK_LOANS(
	BOOK_ID INTEGER NOT NULL,
	BRANCH_ID INTEGER NOT NULL,
	CARD_NO INTEGER NOT NULL,
	DATE_OUT DATE NOT NULL,
	DUE_DATE DATE NOT NULL,
	RETURNED_DATE DATE,

	PRIMARY KEY(BOOK_ID, BRANCH_ID, CARD_NO),

	FOREIGN KEY(BOOK_ID) REFERENCES BOOK(BOOK_ID) ON UPDATE CASCADE,
	FOREIGN KEY(BRANCH_ID) REFERENCES LIBRARY_BRANCH(BRANCH_ID) ON UPDATE CASCADE,
	FOREIGN KEY(CARD_NO) REFERENCES BORROWER(CARD_NO) ON UPDATE CASCADE
);



CREATE TABLE IF NOT EXISTS BOOK_COPIES(
	BOOK_ID INT NOT NULL,
	BRANCH_ID INT NOT NULL,
	NO_OF_COPIES INT NOT NULL,

	PRIMARY KEY(BOOK_ID, BRANCH_ID),

	FOREIGN KEY(BOOK_ID) REFERENCES BOOK(BOOK_ID) ON UPDATE CASCADE,
	FOREIGN KEY(BRANCH_ID) REFERENCES LIBRARY_BRANCH(BRANCH_ID) ON UPDATE CASCADE
);



CREATE TABLE IF NOT EXISTS BOOK_AUTHORS(
	BOOK_ID INT NOT NULL,
	AUTHOR_NAME VARCHAR(50) NOT NULL,	

	PRIMARY KEY (BOOK_ID, AUTHOR_NAME),

	FOREIGN KEY(BOOK_ID) REFERENCES BOOK(BOOK_ID) ON UPDATE CASCADE
);




--populating tables with attribute values imported from corresponding tables
.mode csv
.import Book.csv BOOK 
.import Book_Authors.csv BOOK_AUTHORS
.import Book_Copies.csv BOOK_COPIES
.import Book_Loans.csv BOOK_LOANS
.import Borrower.csv BORROWER
.import Library_Branch.csv LIBRARY_BRANCH
.import Publisher.csv PUBLISHER




