.mode table
.header on

ALTER TABLE LIBRARY_BRANCH ADD COLUMN LATE_FEE DECIMAL(4,2);

UPDATE LIBRARY_BRANCH
SET LATE_FEE =
	CASE 
		WHEN BRANCH_ID = 1 THEN 1
		WHEN BRANCH_ID = 2 THEN 2
		WHEN BRANCH_ID = 3 THEN 3
		WHEN BRANCH_ID = 4 THEN 4
		WHEN BRANCH_ID = 5 THEN 5
END;


