.mode table
.header on

WITH RETURNED AS
(SELECT BL.BRANCH_ID, COUNT(*) AS TOTAL_RETURNED
FROM BOOK_LOANS BL
WHERE RETURNED_DATE IS NOT NULL AND JULIANDAY(RETURNED_DATE) <= JULIANDAY(DUE_DATE)
GROUP BY BL.BRANCH_ID),

LATE_RETURNED AS
(SELECT BL.BRANCH_ID, COUNT(*) AS TOTAL_LATE_RETURNED
FROM BOOK_LOANS BL
WHERE RETURNED_DATE IS NOT NULL AND JULIANDAY(RETURNED_DATE) > JULIANDAY(DUE_DATE)
GROUP BY BL.BRANCH_ID),

STILL_BORROWED AS
(SELECT BL.BRANCH_ID, COUNT(*) AS TOTAL_NOT_RETURNED
FROM BOOK_LOANS BL
WHERE RETURNED_DATE IS NULL
GROUP BY BL.BRANCH_ID)

SELECT LB.BRANCH_NAME, 
	IFNULL(R.TOTAL_RETURNED, 0) AS RETURNED, 
	IFNULL(LR.TOTAL_LATE_RETURNED, 0) AS LATE_RETURNED, 
	IFNULL(SB.TOTAL_NOT_RETURNED, 0) AS STILL_BORROWED

FROM LIBRARY_BRANCH LB
LEFT JOIN RETURNED R ON LB.BRANCH_ID = R.BRANCH_ID
LEFT JOIN LATE_RETURNED LR ON LB.BRANCH_ID = LR.BRANCH_ID
LEFT JOIN STILL_BORROWED SB ON LB.BRANCH_ID = SB.BRANCH_ID
GROUP BY LB.BRANCH_NAME;



