.mode table
.header on

/*
SELECT B.TITLE, LB.BRANCH_NAME,
	
	(CAST(
		  SUBSTR(BL.RETURNED_DATE, (INSTR(BL.RETURNED_DATE, '/')+ 1),
		  		INSTR(SUBSTR(BL.RETURNED_DATE, INSTR(BL.RETURNED_DATE, '/') + 1), '/') -1)
		  AS INTEGER) -

	CAST(
		  SUBSTR(BL.DATE_OUT, (INSTR(BL.DATE_OUT, '/')+ 1),
		  		INSTR(SUBSTR(BL.DATE_OUT, INSTR(BL.DATE_OUT, '/') + 1), '/') -1)
		  AS INTEGER)) AS NO_DAYS_BORROWED

FROM BOOK B NATURAL JOIN BOOK_LOANS BL 
	NATURAL JOIN LIBRARY_BRANCH LB 

WHERE BL.DATE_OUT LIKE '3/%/2022' 
AND CAST(
		  SUBSTR(BL.DATE_OUT, (INSTR(BL.DATE_OUT, '/')+ 1),
		  		INSTR(SUBSTR(BL.DATE_OUT, INSTR(BL.DATE_OUT, '/') + 1), '/') -1)
		  AS INTEGER) 
BETWEEN 5 AND 23;
*/






SELECT B.TITLE, LB.BRANCH_NAME, 
	CAST(
		JULIANDAY(BL.RETURNED_DATE) - JULIANDAY(BL.DATE_OUT) AS INTEGER)
	 AS DAYS_BORROWED

FROM BOOK B NATURAL JOIN BOOK_LOANS BL 
	NATURAL JOIN LIBRARY_BRANCH LB 
WHERE BL.DATE_OUT BETWEEN '2022-03-05' AND '2022-03-23';


