
INSERT INTO LIBRARY_BRANCH(BRANCH_NAME, BRANCH_ADDRESS)
VALUES ('North Branch', '456 NW, Irving, TX 76100');

INSERT INTO LIBRARY_BRANCH(BRANCH_NAME, BRANCH_ADDRESS)
VALUES ('UTA Branch', '123 Cooper St, Arlington TX 76101');


